import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'cvangular';

  personalData: any = {
    name: 'Federico',
    secondName: 'Martin',
    lastname: 'Molinero',
    city: 'Rosario, Argentina',
    position: 'Frontend Developer',
    aboutDescription1: 'Experienced tech professional proficient in full-stack web development, application support, and user management platforms.',
    aboutDescription2: 'Skilled in front end development building responsive, interactive designs adhering to web accessibility guidelines.',
    aboutDescription3: 'Proficient in leading teams and deploying applications on cloud platforms like Azure and AWS.',
    aboutDescription4: 'Passionate about leveraging technology to drive innovation and enhance user experiences.',
    job1: {
      companyName: 'Globant',
      companyLogo: '../assets/globant_logo.jpg',
      jobTitle: 'Web User Interface Developer',
      worktime: 'jun. 2019 - sept. 2023 · (4 yr 4 mo)',
      jobPlace: 'Rosario, Santa Fe, Argentina',
      jobType: 'Hybrid',
      jobRange: 'Full time',
      jobDescription1: 'Full-stack web development, application support, and user management platforms.',
      jobDescription2: 'UI design and development following custom models, with a focus on building responsive, interactive designs adhering to web accessibility guidelines.',
      jobDescription3: 'Implementing and maintaining scalable and performant Angular-based frontends, utilizing web technologies and agile methodologies with distributed teams globally.',
      jobDescription4: 'APIs interacting, conducting research for new development solutions, and contributing to collaborative software development.',
      jobDescription5: 'At Globant, I had the privilege of serving esteemed global enterprises, including leading firms such as EY and PwC. I crafted innovative, bespoke solutions tailored to meet their unique needs, contributing to their business success in a dynamic and competitive landscape',
      workAptitudes: [
        'Web Design',
        'Node.js',
        'Angular',
        'Javascript',
        'Typescript',
        'Cascading Style Sheets (CSS)',
        'Angular Material',
        'Bootstrap',
        'HTML5',
        'Cloud Computing',
        'NPM',
        'GIT',
        'Agile Methodologies',
        'Waterfall',
        'Databases',
        'Microsoft Azure',
        'Azure DevOps',
        'API'
      ]
    },
    job2: {
      companyName: 'Accenture',
      companyLogo: '../assets/accenture_logo.jpg',
      jobTitle: 'Data Engineering Analyst',
      worktime: 'Jun 2018 - Jun 2019 · 1 yr 1 mo',
      jobPlace: 'Rosario, Santa Fe, Argentina',
      jobType: 'Hybrid',
      jobRange: 'Full time',
      jobDescription1: 'I played a key role in the development, implementation, and maintenance of applications, employing agile methodologies and collaborating closely with globally distributed teams.',
      jobDescription2: 'My tasks included optimizing databases with large data volumes and tailoring stored procedures.',
      jobDescription3: 'I showcased strong analytical skills in dissecting project requirements, resulting in the creation of web applications with interactive interfaces and responsive designs, enhancing user experiences.',
      jobDescription4: 'Furthermore, I led initiatives to improve performance across various areas, including software architecture, APIs, and web services.',
      workAptitudes: [
        'Node.js',
        'AWS',
        'GIT',
        'Cloud Computing',
        'Databases',
        'NPM',
        'Angular',
        'Javascript',
        'HTML5',
        'Cascading Style Sheets (CSS)',
        'Web Design',
        'Typescript',
        'Agile & Waterfall Methodologies',
        'API',
      ]
    },
    job3: {
      companyName: 'MundoIT',
      companyLogo: '../assets/mundoit_logo.jpg',
      jobTitle: 'Implementation Analyst',
      worktime: 'Jun 2016 - Nov 2017 · 1 yr 6 mo',
      jobPlace: 'Rosario, Santa Fe, Argentina',
      jobType: 'On-site',
      jobRange: 'Full time',
      jobDescription1: 'Specialized in programming, development, and technical support for applications utilizing web technologies.',
      jobDescription2: 'Conducted thorough functional analyses to understand requirements.',
      jobDescription3: 'Oversaw the normalization of complex data, managed database migrations, and handled modifications and maintenance.',
      jobDescription4: 'Ensured comprehensive documentation and monitored version control to track changes effectively.',
      workAptitudes: [
        'SysAdmin',
        'PHP',
        'Cascading Style Sheets (CSS)',
        'HTML5',
        'Application Support',
        'Javascript',
        'GIT',
        'MySQL',
        'Cloud Computing',
        'Databases',
        'NPM',
        'Web Design',
        'User Management',
        'API',
      ]
    },
    job4: {
      companyName: 'Superintendencia de Riesgos del Trabajo (MTESS)',
      companyLogo: '../assets/srtargentina_logo.jpg',
      jobTitle: 'Fullstack Developer',
      worktime: 'May 2014 - Apr 2016 · 2 yrs',
      jobPlace: 'Rosario, Santa Fe, Argentina',
      jobType: 'On-site',
      jobRange: 'Full time',
      jobDescription1: 'I played a central role in the entire lifecycle of project, from analysis and design to programming, modification, and testing of application, user interfaces, ABM, widgets, statistics and documentation.',
      jobDescription2: 'Additionally, I standardized complex information, managed databases, and developed calculation procedures. I handled platform administration, user permissions, and roles. ',
      jobDescription3: 'Notably, I showcased my capacity to initiate projects from inception, exemplified by leading the development of a nationwide software solution for statistical analysis and issue tracking in the workplace.',
      workAptitudes: [
        'PHP',
        'Ubuntu',
        'Web Design',
        'User Management',
        'Javascript',
        'MySQL',
        'GIT',
        'HTML5',
        'Cascading Style Sheets (CSS)',
        'Cloud Computing',
        'Application Support',
        'SysAdmin',
        'Databases',
        'NPM',
        'API',
      ]
    }

  }


}
